import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { HelpCircle, Award, BrainCircuit, MessageSquareQuote } from "lucide-react"
export function HowToPlayDialog() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" className="absolute top-4 right-4 bg-brand-off-white/50 border-brand-purple/20 hover:bg-brand-off-white">
          <HelpCircle className="mr-2 h-4 w-4" /> How to Play
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[480px] bg-brand-off-white text-brand-purple">
        <DialogHeader>
          <DialogTitle className="text-3xl font-display text-center">How to Play Promptle</DialogTitle>
          <DialogDescription className="text-center text-muted-foreground pt-2">
            Unleash your inner AI artist and guess the magic words!
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-6 py-4 text-left">
          <div className="flex items-start gap-4">
            <div className="p-2 bg-brand-pink/10 rounded-full">
              <BrainCircuit className="h-6 w-6 text-brand-pink" />
            </div>
            <div>
              <h3 className="font-semibold">See the Image</h3>
              <p className="text-sm text-muted-foreground">
                Each day, a new image generated by an AI is revealed. Study its details, style, and subject.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="p-2 bg-brand-pink/10 rounded-full">
              <MessageSquareQuote className="h-6 w-6 text-brand-pink" />
            </div>
            <div>
              <h3 className="font-semibold">Guess the Prompt</h3>
              <p className="text-sm text-muted-foreground">
                Write a prompt that you think could have created the image. Think about keywords, style, and composition.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="p-2 bg-brand-pink/10 rounded-full">
              <Award className="h-6 w-6 text-brand-pink" />
            </div>
            <div>
              <h3 className="font-semibold">Get Your Score</h3>
              <p className="text-sm text-muted-foreground">
                Your score is based on how many keywords from your guess match the original prompt.
              </p>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}